### ISSUE TITLE
Choose and configure comments system

### ISSUE THREAD

**Issue by marian-vignau** [facundobatista/blog#13]

**Comment by facundobatista** [comment]
We'll go for Disqus! Need to open an account there...

**Comment by facundobatista** [comment]
Anda muy bien lo de los comentarios!

Cosas que faltan o no funcionan del todo bien:

- Desde [la pag del índice](http://beta.taniquetil.com.ar/), si hago click en el iconito de comentarios de un post, NO va a un lugar con los comentarios del post, sino que se queda por ahí

- Algunos comentarios de los posts tienen el nombre "raro", mirá [acá](http://beta.taniquetil.com.ar/posts/0053/), un comentario de Mam&#225 en lugar de Mamá...

**Comment by facundobatista** [comment]
Ok, Disqus parece que no anda...

Veamos intensdebate.com !!

**Comment by facundobatista** [comment]
Aguante Isso
