### ISSUE TITLE
Publish post's lists per month & year.

### ISSUE THREAD

**Issue by marian-vignau** [facundobatista/blog#2]
Create a Nikola's plugin that will refresh lists on every commit

**Comment by facundobatista** [comment]
La idea es tener una URL que muestre los posts por año y mes.

Ejemplo:

  http://www.taniquetil.com.ar/plog/archives/1/201006

Un detalle es que en esta "vista", la idea es que NO haya paginación. Si en ese mes hay 7 posts cortos o algunos muy largos, no importa, hay que mostrar todo el contenido hasta el final.

En la barra del costado hay que incluir un listado de los años/meses, hoy está hecho con un combobox, puede quedar así también (pero esta tarea es más para el issue del sidebar que para esta)

**Comment by facundobatista** [comment]
Fixed by PR #18
